trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '<Azure_subscription_1>'
  resourceGroup: '8CLD201_TP2'
  location: 'eastus'
  storageAccountName: '0001storageaccount0001'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Créer le groupe de ressources
      az group create --name $(resourceGroup) --location $(location)

      # Déployer le Storage Account
      az storage account create \
        --name $(storageAccountName) \
        --resource-group $(resourceGroup) \
        --location $(location) \
        --sku Standard_LRS
