trigger:
- main

pool:
  name: Newpool

variables:
  resourceGroupName: '8CLD_201'
  location: 'eastus'
  storageAccountName: '0001storageaccount0001'

stages:
- stage: Infrastructure
  displayName: Déploiement de l'infrastructure
  jobs:
  - job: DeployInfrastructure
    displayName: Déploiement des ressources Azure
    steps:
    - script: |
        az --version
        pwsh --version
      displayName: 'Vérifier les versions de CLI et Shell'

    - task: AzureCLI@2
      displayName: Déployer le groupe de ressources et le Storage Account
      inputs:
        azureSubscription: '01'  # Vérifiez que la connexion Azure est correcte
        scriptType: pscore  # Utiliser PowerShell Core (pscore) au lieu de bash
        scriptLocation: inlineScript
        inlineScript: |
          Write-Host "Création du groupe de ressources"
          az group create --name $Env:resourceGroupName --location $Env:location

          Write-Host "Création du Storage Account"
          az storage account create `
            --name $Env:storageAccountName `
            --resource-group $Env:resourceGroupName `
            --location $Env:location `
            --sku Standard_LRS