trigger:
- main

pool:
  name: Newpool

variables:
  resourceGroupName: '8CLD_201'
  location: 'eastus'
  storageAccountName: '0001storageaccount0001'
  storageContainerName: 'mycontainer'  # Add the missing variable for the container name

stages:
- stage: Infrastructure
  displayName: Déploiement de l'infrastructure
  jobs:
  - job: DeployInfrastructure
    displayName: Déploiement des ressources Azure
    steps:
    - script: |
        az --version
        bash --version
        pwsh --version
      displayName: 'Check CLI and Shell Versions'

    - task: AzureCLI@2
      displayName: Déployer le groupe de ressources et le Storage Account
      inputs:
        azureSubscription: '01'  # Make sure the service connection is correct
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Création du groupe de ressources"
          az group create --name $(resourceGroupName) --location $(location)

          echo "Création du Storage Account"
          az storage account create \
            --name $(storageAccountName) \
            --resource-group $(resourceGroupName) \
            --location $(location) \
            --sku Standard_LRS

          echo "Création du container"
          az storage container create \
            --name $(storageContainerName) \
            --account-name $(storageAccountName)